@startuml
!include style.puml
'skinparam arrowThickness 1.1
'skinparam arrowColor LOGIC_COLOR_T4
'skinparam classBackgroundColor LOGIC_COLOR

hide members
left to right direction

class Command
class CommandResult

package AbstractCommand {
    abstract class ItemCommand
    'Create
    abstract class AddCommand<Item>
    'Read
    abstract class InfoCommand<Item>
    abstract class ListCommand<Item>
    abstract class FilterCommand<Item>
    'Update
    abstract class EditCommand<Item>
    'Delete
    abstract class DeleteCommand<Item>
    abstract class ClearCommand<Item>
}

package ContactCommand {
    'Create
    class AddContactCommand
    'Read
    class InfoContactCommand
    class ListContactCommand
    class FilterContactCommand
    'Update
    class EditContactCommand
    class AddTagToContactCommand
    class RemoveTagFromContactCommand
    'Delete
    class DeleteContactCommand
    class ClearContactCommand
}
package EventCommand {
    'Create
    class AddEventCommand
    'Read
    class InfoEventCommand
    class ListEventCommand
    class FilterEventCommand
    'Update
    class EditEventCommand
    class AddPersonToEventCommand
    class RemovePersonFromEventCommand
    class AddPersonToLogEventCommand
    class RemovePersonFromLogEventCommand
    class AddTagToEventCommand
    class RemoveTagFromEventCommand
    'Delete
    class DeleteEventCommand
    class ClearEventCommand
}
package TodoCommand {
    'Create
    class AddTodoCommand
    'Read
    class InfoTodoCommand
    class ListTodoCommand
    class FilterTodoCommand
    'Update
    class EditTodoCommand
    class AddPersonToTodoCommand
    class RemovePersonFromTodoCommand
    class MarkTodoAsDoneCommand
    class MarkTodoAsNotDoneCommand
    class AddTagToTodoCommand
    class RemoveTagFromTodoCommand
    'Delete
    class DeleteTodoCommand
    class ClearTodoCommand
}

'skinparam nodesep 50
'skinparam ranksep 50


'Abstract are instances of ItemCommand which implements Command
ItemCommand --|> Command
AddCommand --|> ItemCommand
DeleteCommand --|> ItemCommand
InfoCommand --|> ItemCommand
ListCommand --|> ItemCommand
FilterCommand --|> ItemCommand
ClearCommand --|> ItemCommand
EditCommand --|> ItemCommand

'Execution of command gives CommandResult
Command --> CommandResult : on execution gives >

'Concrete for Contact
AddContactCommand --|> AddCommand
InfoContactCommand --|> InfoCommand
ListContactCommand --|> ListCommand
FilterContactCommand --|> FilterCommand
EditContactCommand --|> EditCommand
AddTagToContactCommand --|> EditCommand
RemoveTagFromContactCommand --|> EditCommand
DeleteContactCommand --|> DeleteCommand
ClearContactCommand --|> ClearCommand

'Concrete for Event
AddEventCommand --|> AddCommand
InfoEventCommand --|> InfoCommand
ListEventCommand --|> ListCommand
FilterEventCommand --|> FilterCommand
EditEventCommand --|> EditCommand
AddPersonToEventCommand --|> EditCommand
RemovePersonFromEventCommand --|> EditCommand
AddPersonToLogEventCommand --|> EditCommand
RemovePersonFromLogEventCommand --|> EditCommand
AddTagToEventCommand --|> EditCommand
RemoveTagFromEventCommand --|> EditCommand
DeleteEventCommand --|> DeleteCommand
ClearEventCommand --|> ClearCommand

'Concrete for Todo
AddTodoCommand --|> AddCommand
InfoTodoCommand --|> InfoCommand
ListTodoCommand --|> ListCommand
FilterTodoCommand --|> FilterCommand
EditTodoCommand --|> EditCommand
AddPersonToTodoCommand --|> EditCommand
RemovePersonFromTodoCommand --|> EditCommand
MarkTodoAsDoneCommand --|> EditCommand
MarkTodoAsNotDoneCommand --|> EditCommand
AddTagToTodoCommand --|> EditCommand
RemoveTagFromTodoCommand --|> EditCommand
DeleteTodoCommand --|> DeleteCommand
ClearTodoCommand --|> ClearCommand

@enduml
