@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ParserImpl" as ParserImpl LOGIC_COLOR
participant ":ContactCommandParser" as ContactCommandParser LOGIC_COLOR
participant ":DeleteContactCommandParser" as DeleteContactCommandParser LOGIC_COLOR
participant "d:DeleteContactCommand" as DeleteContactCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("contact delete 1")
activate LogicManager

LogicManager -> ParserImpl : parseCommand("contact delete 1")
activate ParserImpl

create ContactCommandParser
ParserImpl -> ContactCommandParser :parseCommand("delete 1")
activate ContactCommandParser

create DeleteContactCommandParser
ContactCommandParser -> DeleteContactCommandParser : parse("1")
activate DeleteContactCommandParser

create DeleteContactCommand
DeleteContactCommandParser -> DeleteContactCommand
activate DeleteContactCommand

'Return to LogicManager
DeleteContactCommand --> DeleteContactCommandParser : d
deactivate DeleteContactCommand

DeleteContactCommandParser --> ContactCommandParser : d
deactivate DeleteContactCommandParser

ContactCommandParser --> ParserImpl : d
deactivate ContactCommandParser
destroy DeleteContactCommandParser

ParserImpl --> LogicManager : d
deactivate ParserImpl
destroy ContactCommandParser

'Hidden arrow to position the destroy marker below the end of the activation bar.

DeleteContactCommandParser -[hidden]-> ParserImpl

LogicManager -> DeleteContactCommand : execute(m)
activate DeleteContactCommand

DeleteContactCommand -> Model : deleteContact(1)
activate Model

Model --> DeleteContactCommand
deactivate Model

create CommandResult
DeleteContactCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteContactCommand
deactivate CommandResult

DeleteContactCommand --> LogicManager : r
deactivate DeleteContactCommand

[<--LogicManager
deactivate LogicManager
@enduml
