@startuml
allow_mixing
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{
Class "{abstract}\nItemManagerWithFilteredList" as ManagerAndList<T extends Item>
Class "{abstract}\nItemManager" as Manager<T extends Item>
Class FilteredList<T extends Item>
Class "{abstract}\nUniqueItemList" as List<T extends Item>
Class TManagerWithFilteredList
Class TManager
Class UniqueTList
Class T
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class ModelManager
Class UserPrefs
}

Cloud HiddenOutside
HiddenOutside ..> Model

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .right.> ManagerAndList
TManagerWithFilteredList .right.|> ManagerAndList
ModelManager -left-> "1" ManagerAndList
ModelManager .left.> TManagerWithFilteredList
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs
ManagerAndList -down-> "1" Manager
ManagerAndList -down-> "1" FilteredList
TManager .right.|> Manager
TManagerWithFilteredList .down.> TManager
Manager -down-> "1" List
UniqueTList .right.|> List
TManager .down.> UniqueTList
List -down-> "*" T
FilteredList -down-> "filtered *" T
UniqueTList .down.> T
@enduml
