@startuml
!include style.puml
allowmixing
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

Class "{abstract}\nCommand" as Command
Class XYZCommand

package "Parser classes"{
Class "<<interface>>\nParser" as Parser
Class ParserImpl
Class XYZCommandParser
Class CliSyntax
Class ParserUtil
Class ArgumentMultimap
Class ArgumentTokenizer
Class PrefixAlias
class Prefix
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> ParserImpl

ParserImpl .down.> XYZCommandParser: <<create>>

XYZCommandParser ..> XYZCommand : <<create>>
ParserImpl ..> Command : <<use>>
XYZCommandParser .up.|> Parser
XYZCommandParser ..> ArgumentMultimap
XYZCommandParser ..> ArgumentTokenizer
ArgumentTokenizer .left.> ArgumentMultimap
XYZCommandParser ..> CliSyntax
CliSyntax ..> PrefixAlias
XYZCommandParser ..> ParserUtil
ParserUtil .down.> PrefixAlias
ArgumentTokenizer .down.> PrefixAlias
PrefixAlias -.right.> Prefix
XYZCommand -up-|> Command
@enduml
