@startuml
!include style.puml
allowmixing
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

Class "{abstract}\nCommand" as Command
Class XYCommand

package "Parser classes"{
Class "<<interface>>\nParser" as Parser
Class ParserImpl
Class XYCommandParser
Class CliSyntax
Class ParserUtil
Class ArgumentMultimap
Class ArgumentTokenizer
Class PrefixAlias
class Prefix
}

Cloud HiddenOutside #FFFFFF
HiddenOutside ..> ParserImpl

ParserImpl .down.> XYCommandParser: <<create>>

XYCommandParser ..> XYCommand : <<create>>
ParserImpl ..> Command : <<use>>
XYCommandParser .up.|> Parser
XYCommandParser ..> ArgumentMultimap
XYCommandParser ..> ArgumentTokenizer
ArgumentTokenizer .left.> ArgumentMultimap
XYCommandParser ..> CliSyntax
CliSyntax ..> PrefixAlias
XYCommandParser ..> ParserUtil
ParserUtil .down.> PrefixAlias
ArgumentTokenizer .down.> PrefixAlias
PrefixAlias -.right.> Prefix
XYCommand -up-|> Command
@enduml
