@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>> {
Class "<<interface>>\nUi" as Ui
Class "{abstract}\nUiPart<T>" as UiPart
Class UiManager
Class MainWindow
Class ResultDisplay
Class CommandBox
Class ListPanel
Class DisplayableListViewCell

package "card" as card {
Class "<<interface>>\nCard<T>" as Card
Class "<<interface>>\nCardFactory<T>" as CardFactory
Class XCard
}

Class "<<interface>>\nDisplayableItem" as DisplayableItem
}

package Model <<Rectangle>> {
Class X
Class HiddenModelInterface #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow
MainWindow *-down-> "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow *-down-> "1" ListPanel

MainWindow -left-|> UiPart
ResultDisplay --|> UiPart
CommandBox --|> UiPart
ListPanel --|> UiPart

XCard -right-|> UiPart

X ..|> DisplayableItem
XCard .down.|> Card

ListPanel --> "*" DisplayableItem : displays >
DisplayableListViewCell -> DisplayableItem : renders
Card ..> DisplayableItem : < getDisplayCard() creates
CardFactory .left.> Card : creates >

XCard --> X : references >

UiManager -right-> Logic
MainWindow -left-> Logic

@enduml