@startuml
!include style.puml
skinparam ArrowFontStyle plain

participant ":XYCommandParser" as  CommandParser LOGIC_COLOR
participant "<<Class>>\n ArgumentTokenizer" as ArgTokenizer LOGIC_COLOR
participant "c:XYCommand" as EditCommand LOGIC_COLOR
participant "a:ArgumentMultimap" as ArgumentMultimap LOGIC_COLOR
participant ":XYParserUtil" as ParserUtil LOGIC_COLOR

[-> CommandParser : parse(args)
activate CommandParser
CommandParser -> ArgTokenizer : tokenize(args, prefixes)
activate ArgTokenizer

ArgTokenizer --> ArgTokenizer: findAllPrefixPositions(argsString, Prefix ...prefixes)
activate ArgTokenizer
ArgTokenizer --> ArgTokenizer: findPrefixPositions(argsString, Prefix ...prefixes)
activate ArgTokenizer
ArgTokenizer --> ArgumentMultimap
deactivate ArgTokenizer
activate ArgumentMultimap
ArgumentMultimap --> ArgumentMultimap : extractArguments(argStrings, position)
ArgumentMultimap --> ArgTokenizer
deactivate ArgTokenizer
deactivate ArgumentMultimap

ArgTokenizer --> CommandParser : a
deactivate ArgTokenizer

CommandParser --> ParserUtil : parseAttribute(args)
activate ParserUtil
ParserUtil --> CommandParser : attribute
deactivate ParserUtil

create EditCommand
CommandParser --> EditCommand : XCommand(index, contactIndices)
activate EditCommand
EditCommand --> CommandParser : c
deactivate EditCommand
[<-- CommandParser : c
@enduml
